// Code generated by ginctl. DO NOT EDIT.

package router

import (
	"{{.gomod}}/config"
	"fmt"

	"github.com/gin-gonic/gin"
)

func StartGinServer() {
	if config.AppConf.GinRelease {
		gin.SetMode(gin.ReleaseMode)
	}
	engine := gin.New()
	engine.Use(
		gin.Recovery(),
		gin.Logger(),
	)
	CustomRegister(engine)
	AutoRegister(engine)
	err := engine.Run(fmt.Sprintf("%s:%s", config.AppConf.Host, config.AppConf.Port))
	if err != nil {
		panic(err)
	}
}